version: '3'
services:
    php:
        image: php:7.4-cli-alpine
        restart: always
        environment:
            - WATTPAD_ENV=local
        volumes:
            - ".:/var/mini-wiki:delegated"
            - "./etc/php/php.ini:/usr/local/etc/php/php.ini"
        ports:
            - "127.0.0.1:9081:9081"
        working_dir: /var/mini-wiki/app/public
        command: php -S 0.0.0.0:9081 router.php
